dependencies = []
description = "Unofficial Terraform provider for Outscale"
destination_server = []
flags = ["devops", "sdk", "tools"]
languages = ["go"]
owner = "team-infrastructure-engineering@scalingo.com"
team = "IET"
version = "0.0.1"
tier = 1
